name: llm_dart_workspace
description: Workspace root for the llm_dart monorepo (not published).
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - packages/llm_dart
  - packages/llm_dart_ai
  - packages/llm_dart_anthropic
  - packages/llm_dart_anthropic_compatible
  - packages/llm_dart_builder
  - packages/llm_dart_core
  - packages/llm_dart_deepseek
  - packages/llm_dart_elevenlabs
  - packages/llm_dart_google
  - packages/llm_dart_groq
  - packages/llm_dart_minimax
  - packages/llm_dart_ollama
  - packages/llm_dart_openai
  - packages/llm_dart_openai_compatible
  - packages/llm_dart_phind
  - packages/llm_dart_provider_utils
  - packages/llm_dart_xai

dev_dependencies:
  logging: ^1.2.0
  llm_dart: ^0.11.0-alpha.1
  llm_dart_ai: ^0.11.0-alpha.1
  llm_dart_builder: ^0.11.0-alpha.1
  llm_dart_core: ^0.11.0-alpha.1
  llm_dart_provider_utils: ^0.11.0-alpha.1
  llm_dart_openai: ^0.11.0-alpha.1
  llm_dart_openai_compatible: ^0.11.0-alpha.1
  llm_dart_anthropic_compatible: ^0.11.0-alpha.1
  llm_dart_anthropic: ^0.11.0-alpha.1
  llm_dart_google: ^0.11.0-alpha.1
  llm_dart_deepseek: ^0.11.0-alpha.1
  llm_dart_ollama: ^0.11.0-alpha.1
  llm_dart_xai: ^0.11.0-alpha.1
  llm_dart_groq: ^0.11.0-alpha.1
  llm_dart_elevenlabs: ^0.11.0-alpha.1
  llm_dart_minimax: ^0.11.0-alpha.1
  dio: ^5.9.0
  test: ^1.27.0
  mockito: ^5.4.0
  mcp_dart: ^0.6.3
  lints: ^6.0.0
  yaml: ^3.1.3
