name: llm_dart_openai
description: OpenAI provider implementation for llm_dart, including chat, embeddings, audio, images, files, moderation and Responses API.
version: 0.11.0-rc.1

homepage: https://github.com/Latias94/llm_dart
repository: https://github.com/Latias94/llm_dart
issue_tracker: https://github.com/Latias94/llm_dart/issues

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dio: ^5.9.0
  llm_dart_core: ^0.11.0-rc.1
  llm_dart_provider_utils: ^0.11.0-rc.1
  http_parser: ^4.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
